// the errors that can be thrown by the package
export const ERRORS = {
  INVALID_TEMPLATE_NAME: 'INVALID_TEMPLATE_NAME',
  NOT_A_PATH_ELEMENT: 'NOT_A_PATH_ELEMENT',
  FAILED_TO_READ_BASE_CONFIG: 'FAILED_TO_READ_BASE_CONFIG',
  INVALID_FIREBASE_CONFIG: 'INVALID_FIREBASE_CONFIG',
  INVALID_ENVIRONMENT: 'INVALID_ENVIRONMENT',
  FAILED_TO_BUILD_CONFIG: 'FAILED_TO_BUILD_CONFIG',
  FAILED_TO_READ_FIREBASE_CONFIG: 'FAILED_TO_READ_FIREBASE_CONFIG',
} as const;
